version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd src/mysite/
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app